DROP TABLE T_INITIAL_KD
/
DROP TABLE T_INITIAL_KD_BACKUP
/
DROP TABLE T_IN_OUT_KD
/
DROP TABLE T_IN_OUT_KD_BACKUP
/
DROP TABLE T_LOCATION_MASTER_KD
/
DROP TABLE T_LOCATION_MASTER_KD_BACKUP
/
DROP TABLE T_NOT_ENTRY_KD
/
DROP TABLE T_PIC_MASTER_KD
/
DROP TABLE T_PIC_MASTER_KD_BACKUP
/
DROP TABLE T_PRODUCTS_KD
/
DROP TABLE T_PRODUCTS_KD_BACKUP
/
DROP SEQUENCE T_IN_OUT_KD_BACKUP_SEQ
/
DROP SEQUENCE T_IN_OUT_KD_SEQ
/
DROP SEQUENCE T_NOT_ENTRY_KD_SEQ
/
DROP PACKAGE PKG_KD_APP
/
DROP PACKAGE PKG_KD_DELETE_OLD_DATA
/
DROP PACKAGE PKG_KD_DRS
/
DROP PACKAGE PKG_KD_RESET_DEMO_DATA
/
--過去データ削除JOB無効化
BEGIN
    DBMS_SCHEDULER.DISABLE('JOB_KD_DELETE_OLD_DATA');
END;
/
--過去データ削除JOB削除
BEGIN
    DBMS_SCHEDULER.DROP_JOB('JOB_KD_DELETE_OLD_DATA');
END;
/
--デモデータ削除JOB無効化
BEGIN
    DBMS_SCHEDULER.DISABLE('JOB_KD_RESET_DEMO_DATA');
END;
/
--デモデータ削除JOB削除
BEGIN
    DBMS_SCHEDULER.DROP_JOB('JOB_KD_RESET_DEMO_DATA');
END;
/
